CREATE TABLE IF NOT EXISTS account (
  id INTEGER PRIMARY KEY,
  cash_balance DOUBLE PRECISION NOT NULL,
  initial_balance DOUBLE PRECISION NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS position (
  pair TEXT PRIMARY KEY,
  quantity DOUBLE PRECISION NOT NULL,
  avg_cost DOUBLE PRECISION NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS trade (
  id BIGSERIAL PRIMARY KEY,
  pair TEXT NOT NULL,
  side TEXT NOT NULL CHECK (side IN ('buy', 'sell')),
  quantity DOUBLE PRECISION NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  notional DOUBLE PRECISION NOT NULL,
  fee DOUBLE PRECISION NOT NULL,
  realized_pnl DOUBLE PRECISION NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
